#!/bin/bash

python load_database.py -jf ../android-callgraph/output/air.intergraphics.mentalMath.Multiplication.Demo-4000000.apk.cg.txt -app air.intergraphics.mentalMath.Multiplication.Demo-4000000.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/air.WatchESPN-2100049.apk.cg.txt -app air.WatchESPN-2100049.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/alpha.aquarium.hd.livewallpaper.apk.cg.txt -app alpha.aquarium.hd.livewallpaper.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/bn.ereader.apk.cg.txt -app bn.ereader.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.accuweather.android.apk.cg.txt -app com.accuweather.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.adobe.psmobile-18.apk.cg.txt -app com.adobe.psmobile-18.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.adsk.instructables-2000004.apk.cg.txt -app com.adsk.instructables-2000004.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.alensw.PicFolder-154.apk.cg.txt -app com.alensw.PicFolder-154.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.amazon.kindle.apk.cg.txt -app com.amazon.kindle.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.anddoes.fancywidgets-22.apk.cg.txt -app com.anddoes.fancywidgets-22.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.andromo.dev230101.app300711-10.apk.cg.txt -app com.andromo.dev230101.app300711-10.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.audible.application.apk.cg.txt -app com.audible.application.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.augmentra.viewranger.android.apk.cg.txt -app com.augmentra.viewranger.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.autodesk.homestyler-42.apk.cg.txt -app com.autodesk.homestyler-42.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.aviary.android.feather.plugins.borders.free-2.apk.cg.txt -app com.aviary.android.feather.plugins.borders.free-2.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.aviary.android.feather.plugins.stickers.free_stickers-1.apk.cg.txt -app com.aviary.android.feather.plugins.stickers.free_stickers-1.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.aws.android.apk.cg.txt -app com.aws.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.axiemsystems.photoeditorminus-110.apk.cg.txt -app com.axiemsystems.photoeditorminus-110.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.baiwang.instablend-20.apk.cg.txt -app com.baiwang.instablend-20.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.banjo.android-68.apk.cg.txt -app com.banjo.android-68.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.baseapp.eyeem.apk.cg.txt -app com.baseapp.eyeem.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.basecamp.app-49.apk.cg.txt -app com.basecamp.app-49.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.beatronik.djstudiodemo-114.apk.cg.txt -app com.beatronik.djstudiodemo-114.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.bigduckgames.flow-29.apk.cg.txt -app com.bigduckgames.flow-29.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.booktrack.gelada.edu-7.apk.cg.txt -app com.booktrack.gelada.edu-7.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.box.android.apk.cg.txt -app com.box.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.boxed.prod.apk.cg.txt -app com.boxed.prod.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.brainpop.brainpopfeaturedmovieandroid-16.apk.cg.txt -app com.brainpop.brainpopfeaturedmovieandroid-16.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.brakefield.idfree-59.apk.cg.txt -app com.brakefield.idfree-59.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.bsb.hike.apk.cg.txt -app com.bsb.hike.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.buzzpia.aqua.appwidget.clock-2126.apk.cg.txt -app com.buzzpia.aqua.appwidget.clock-2126.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.campmobile.launcher-69.apk.cg.txt -app com.campmobile.launcher-69.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.carezone.caredroid.careapp.medications-34902.apk.cg.txt -app com.carezone.caredroid.careapp.medications-34902.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.caynax.a6w-80406.apk.cg.txt -app com.caynax.a6w-80406.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.cgames.minesweeper-31.apk.cg.txt -app com.cgames.minesweeper-31.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.chase.sig.android-42.apk.cg.txt -app com.chase.sig.android-42.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.cleanmaster.mguard.apk.cg.txt -app com.cleanmaster.mguard.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.cleanmaster.security.apk.cg.txt -app com.cleanmaster.security.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.cloudmagic.mail-126.apk.cg.txt -app com.cloudmagic.mail-126.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.cnn.mobile.android.phone.apk.cg.txt -app com.cnn.mobile.android.phone.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.concur.breeze-37150220.apk.cg.txt -app com.concur.breeze-37150220.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.cootek.smartinputv5.apk.cg.txt -app com.cootek.smartinputv5.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.coupons.ciapp.apk.cg.txt -app com.coupons.ciapp.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.crunchyroll.crmanga-17.apk.cg.txt -app com.crunchyroll.crmanga-17.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.devuni.flashlight-170.apk.cg.txt -app com.devuni.flashlight-170.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.dietcoacher.sos.apk.cg.txt -app com.dietcoacher.sos.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.discovercircle10-100.apk.cg.txt -app com.discovercircle10-100.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.disney.disneymoviesanywhere_goo-195.apk.cg.txt -app com.disney.disneymoviesanywhere_goo-195.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.drippler.android.updates.apk.cg.txt -app com.drippler.android.updates.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.droid27.transparentclockweather-96.apk.cg.txt -app com.droid27.transparentclockweather-96.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.dropbox.android-240810.apk.cg.txt -app com.dropbox.android-240810.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.dsd164.snake97-8.apk.cg.txt -app com.dsd164.snake97-8.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.ea.game.tetris2011_na-1410.apk.cg.txt -app com.ea.game.tetris2011_na-1410.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.emflag.mahjongmaster-26.apk.cg.txt -app com.emflag.mahjongmaster-26.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.emoji.coolkeyboard-11.apk.cg.txt -app com.emoji.coolkeyboard-11.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.escapistgames.starchart.apk.cg.txt -app com.escapistgames.starchart.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.espn.score_center-595.apk.cg.txt -app com.espn.score_center-595.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.etsy.android.apk.cg.txt -app com.etsy.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.evernote.apk.cg.txt -app com.evernote.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.fancred.android-82.apk.cg.txt -app com.fancred.android-82.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.fatsecret.android.apk.cg.txt -app com.fatsecret.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.fitnesskeeper.runkeeper.pro.apk.cg.txt -app com.fitnesskeeper.runkeeper.pro.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.fitnow.loseit-138.apk.cg.txt -app com.fitnow.loseit-138.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.fivemobile.thescore.apk.cg.txt -app com.fivemobile.thescore.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.fooducate.nutritionapp-212.apk.cg.txt -app com.fooducate.nutritionapp-212.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.foursquare.robin.apk.cg.txt -app com.foursquare.robin.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.foxfi.addon-3011.apk.cg.txt -app com.foxfi.addon-3011.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.foxit.mobile.pdf.lite-18.apk.cg.txt -app com.foxit.mobile.pdf.lite-18.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.foxnews.android-200080.apk.cg.txt -app com.foxnews.android-200080.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.fox.now-2089.apk.cg.txt -app com.fox.now-2089.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.foxsports.android-20.apk.cg.txt -app com.foxsports.android-20.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.frostwire.android.apk.cg.txt -app com.frostwire.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.fsck.k9.apk.cg.txt -app com.fsck.k9.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.gismart.guitar.apk.cg.txt -app com.gismart.guitar.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.goodrx.apk.cg.txt -app com.goodrx.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.google.android.apps.googlevoice-40601.apk.cg.txt -app com.google.android.apps.googlevoice-40601.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.google.android.apps.maps.apk.cg.txt -app com.google.android.apps.maps.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.google.android.apps.messaging.apk.cg.txt -app com.google.android.apps.messaging.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.google.android.apps.walletnfcrel.apk.cg.txt -app com.google.android.apps.walletnfcrel.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.google.android.apps.youtube.kids-70505000.apk.cg.txt -app com.google.android.apps.youtube.kids-70505000.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.google.android.GoogleCamera-24025130.apk.cg.txt -app com.google.android.GoogleCamera-24025130.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.google.android.music.apk.cg.txt -app com.google.android.music.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.google.android.talk.apk.cg.txt -app com.google.android.talk.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.google.samples.apps.cardboarddemo-150210005.apk.cg.txt -app com.google.samples.apps.cardboarddemo-150210005.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.google.zxing.client.android.apk.cg.txt -app com.google.zxing.client.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.gopro.smarty.apk.cg.txt -app com.gopro.smarty.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.gotv.nflgamecenter.us.lite.apk.cg.txt -app com.gotv.nflgamecenter.us.lite.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.groupon.apk.cg.txt -app com.groupon.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.grubhub.android-17000000.apk.cg.txt -app com.grubhub.android-17000000.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.headupgames.bridgeconstructorplaygroundfree-104011.apk.cg.txt -app com.headupgames.bridgeconstructorplaygroundfree-104011.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.hellotext.hello-189.apk.cg.txt -app com.hellotext.hello-189.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.herman.ringtone.apk.cg.txt -app com.herman.ringtone.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.hp.pregnancy.lite-45.apk.cg.txt -app com.hp.pregnancy.lite-45.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.hulu.plus-202193.apk.cg.txt -app com.hulu.plus-202193.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.imo.android.imoim.apk.cg.txt -app com.imo.android.imoim.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.infinut.kindergarten.math.free-540.apk.cg.txt -app com.infinut.kindergarten.math.free-540.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.infonow.bofa-1800602002.apk.cg.txt -app com.infonow.bofa-1800602002.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.infraware.office.link-43.apk.cg.txt -app com.infraware.office.link-43.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.instagram.android.apk.cg.txt -app com.instagram.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.isbx.pasco.Spark-22007.apk.cg.txt -app com.isbx.pasco.Spark-22007.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.jackthreads.android.apk.cg.txt -app com.jackthreads.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.jardogs.fmhmobile-88.apk.cg.txt -app com.jardogs.fmhmobile-88.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.jb.emoji.gokeyboard.apk.cg.txt -app com.jb.emoji.gokeyboard.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.jessdev.socphotoeff-10303.apk.cg.txt -app com.jessdev.socphotoeff-10303.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.joelapenna.foursquared-2015022723.apk.cg.txt -app com.joelapenna.foursquared-2015022723.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.judas.apps.calling.video-2.apk.cg.txt -app com.judas.apps.calling.video-2.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.kicksend.android-470.apk.cg.txt -app com.kicksend.android-470.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.korhaan.sequencer-5.apk.cg.txt -app com.korhaan.sequencer-5.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.krivoz.submangareader-85.apk.cg.txt -app com.krivoz.submangareader-85.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.ksmobile.launcher.apk.cg.txt -app com.ksmobile.launcher.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.lava.music-15.apk.cg.txt -app com.lava.music-15.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.lazyswipe-1611.apk.cg.txt -app com.lazyswipe-1611.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.learninga_z.onyourown-40.apk.cg.txt -app com.learninga_z.onyourown-40.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.liketwice.android-34.apk.cg.txt -app com.liketwice.android-34.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.loudcrow.marvelavengers-3.apk.cg.txt -app com.loudcrow.marvelavengers-3.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.magix.android.mmjam-140011600.apk.cg.txt -app com.magix.android.mmjam-140011600.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.mapmyhike.android2.apk.cg.txt -app com.mapmyhike.android2.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.mapmywalk.android2.apk.cg.txt -app com.mapmywalk.android2.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.mapquest.android.ace.apk.cg.txt -app com.mapquest.android.ace.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.marvel.comics-37033.apk.cg.txt -app com.marvel.comics-37033.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.masteryconnect.NGSS-17.apk.cg.txt -app com.masteryconnect.NGSS-17.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.meetup-188.apk.cg.txt -app com.meetup-188.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.microsoft.office.officehub-15704500.apk.cg.txt -app com.microsoft.office.officehub-15704500.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.microsoft.office.onenote-1532321047.apk.cg.txt -app com.microsoft.office.onenote-1532321047.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.mindframedesign.cheftap.beta-347.apk.cg.txt -app com.mindframedesign.cheftap.beta-347.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.minus.android.apk.cg.txt -app com.minus.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.mobilemotion.dubsmash.apk.cg.txt -app com.mobilemotion.dubsmash.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.mobisystems.office-2741.apk.cg.txt -app com.mobisystems.office-2741.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.mobli.apk.cg.txt -app com.mobli.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.modcloth-75.apk.cg.txt -app com.modcloth-75.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.modelmakertools.simplemindfree-21.apk.cg.txt -app com.modelmakertools.simplemindfree-21.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.mufumbo.android.recipe.search.apk.cg.txt -app com.mufumbo.android.recipe.search.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.muzy-59.apk.cg.txt -app com.muzy-59.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.mxtech.ffmpeg.v7_vfpv3d16-83.apk.cg.txt -app com.mxtech.ffmpeg.v7_vfpv3d16-83.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.mxtech.videoplayer.ad.apk.cg.txt -app com.mxtech.videoplayer.ad.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.myfitnesspal.android.apk.cg.txt -app com.myfitnesspal.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.myyearbook.m.apk.cg.txt -app com.myyearbook.m.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.namcobandaigames.pacmantournaments-101.apk.cg.txt -app com.namcobandaigames.pacmantournaments-101.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.naturalapps.notas-14.apk.cg.txt -app com.naturalapps.notas-14.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.netflix.mediaclient.apk.cg.txt -app com.netflix.mediaclient.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.nextdoor-46.apk.cg.txt -app com.nextdoor-46.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.northpark.drinkwater-74.apk.cg.txt -app com.northpark.drinkwater-74.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.northpark.pushups-57.apk.cg.txt -app com.northpark.pushups-57.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.notabasement.mangarock.android.mckinley-29.apk.cg.txt -app com.notabasement.mangarock.android.mckinley-29.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.okcupid.okcupid.apk.cg.txt -app com.okcupid.okcupid.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.overstock-295000.apk.cg.txt -app com.overstock-295000.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.p1.chompsms-9064206.apk.cg.txt -app com.p1.chompsms-9064206.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.paypal.android.p2pmobile-110005810.apk.cg.txt -app com.paypal.android.p2pmobile-110005810.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.photoaffections.freeprints-3667.apk.cg.txt -app com.photoaffections.freeprints-3667.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.picsart.studio.apk.cg.txt -app com.picsart.studio.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.planeth.rhythm-170.apk.cg.txt -app com.planeth.rhythm-170.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.pof.android.apk.cg.txt -app com.pof.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.popularapp.sevenmins-31.apk.cg.txt -app com.popularapp.sevenmins-31.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.qihoo.security-60.apk.cg.txt -app com.qihoo.security-60.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.quip.quip.apk.cg.txt -app com.quip.quip.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.quoord.tapatalkpro.activity.apk.cg.txt -app com.quoord.tapatalkpro.activity.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.quvideo.xiaoying-62.apk.cg.txt -app com.quvideo.xiaoying-62.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.roveapp.rove-45.apk.cg.txt -app com.roveapp.rove-45.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.rubycell.perfectguitar.apk.cg.txt -app com.rubycell.perfectguitar.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.scripps.android.foodnetwork-403000.apk.cg.txt -app com.scripps.android.foodnetwork-403000.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.shazam.android.apk.cg.txt -app com.shazam.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.singlecellsoftware.caustic-19.apk.cg.txt -app com.singlecellsoftware.caustic-19.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.sirma.mobile.bible.android.apk.cg.txt -app com.sirma.mobile.bible.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.sjInnovation.tpt-4.apk.cg.txt -app com.sjInnovation.tpt-4.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.skimble.workouts-61.apk.cg.txt -app com.skimble.workouts-61.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.SkyDivers.asteroids3d-131.apk.cg.txt -app com.SkyDivers.asteroids3d-131.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.skype.android.qik-5240.apk.cg.txt -app com.skype.android.qik-5240.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.slidelock-58.apk.cg.txt -app com.slidelock-58.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.snapchat.android.apk.cg.txt -app com.snapchat.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.socratica.mobile.learnalphabet.free-15.apk.cg.txt -app com.socratica.mobile.learnalphabet.free-15.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.socrative.teacher-24.apk.cg.txt -app com.socrative.teacher-24.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.somcloud.somnote-2015021518.apk.cg.txt -app com.somcloud.somnote-2015021518.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.sonyericsson.digitalclockwidget2-83.apk.cg.txt -app com.sonyericsson.digitalclockwidget2-83.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.soundcloud.android.apk.cg.txt -app com.soundcloud.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.speaktoit.assistant.apk.cg.txt -app com.speaktoit.assistant.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.squareup.apk.cg.txt -app com.squareup.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.syntomo.email-525060.apk.cg.txt -app com.syntomo.email-525060.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.teachersparadise.iGradr-2.apk.cg.txt -app com.teachersparadise.iGradr-2.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.teamviewer.teamviewer.market.mobile.apk.cg.txt -app com.teamviewer.teamviewer.market.mobile.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.tellagami.Tellagami-51.apk.cg.txt -app com.tellagami.Tellagami-51.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.tenmonkeys.multiplication-3.apk.cg.txt -app com.tenmonkeys.multiplication-3.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.teslacoilsw.launcher-33000.apk.cg.txt -app com.teslacoilsw.launcher-33000.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.textmeinc.textme.apk.cg.txt -app com.textmeinc.textme.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.textra-22692.apk.cg.txt -app com.textra-22692.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.thefancy.app-29601.apk.cg.txt -app com.thefancy.app-29601.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.thetransitapp.droid-1436.apk.cg.txt -app com.thetransitapp.droid-1436.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.timehop-283.apk.cg.txt -app com.timehop-283.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.tmsoft.whitenoise.lite.apk.cg.txt -app com.tmsoft.whitenoise.lite.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.touchtype.swiftkey.apk.cg.txt -app com.touchtype.swiftkey.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.tripadvisor.android.apps.cityguide.catalog-10.apk.cg.txt -app com.tripadvisor.android.apps.cityguide.catalog-10.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.ubercab.apk.cg.txt -app com.ubercab.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.ubercab.driver-39.apk.cg.txt -app com.ubercab.driver-39.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.venticake.retrica-26.apk.cg.txt -app com.venticake.retrica-26.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.viber.voip-89.apk.cg.txt -app com.viber.voip-89.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.visionobjects.calculator.apk.cg.txt -app com.visionobjects.calculator.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.vtcreator.android360.apk.cg.txt -app com.vtcreator.android360.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.walmart.android.apk.cg.txt -app com.walmart.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.WaterfallLiveWallpaperHDHQ-15.apk.cg.txt -app com.WaterfallLiveWallpaperHDHQ-15.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.waze.apk.cg.txt -app com.waze.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.weather.Weather.apk.cg.txt -app com.weather.Weather.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.webprofusion.scalex-10800.apk.cg.txt -app com.webprofusion.scalex-10800.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.wevideo.mobile.android-55.apk.cg.txt -app com.wevideo.mobile.android-55.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.wf.wellsfargomobile-1000401.apk.cg.txt -app com.wf.wellsfargomobile-1000401.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.whaleshark.retailmenot-40301.apk.cg.txt -app com.whaleshark.retailmenot-40301.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.whisperarts.kids.math-16.apk.cg.txt -app com.whisperarts.kids.math-16.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.yahoo.mobile.client.android.mail.apk.cg.txt -app com.yahoo.mobile.client.android.mail.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.yahoo.mobile.client.android.yahoo.apk.cg.txt -app com.yahoo.mobile.client.android.yahoo.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.yelp.android.apk.cg.txt -app com.yelp.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.yoga.pro.google.paid-10050.apk.cg.txt -app com.yoga.pro.google.paid-10050.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.yooiistudios.morningkit-58.apk.cg.txt -app com.yooiistudios.morningkit-58.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/com.zoosk.zoosk.apk.cg.txt -app com.zoosk.zoosk.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/cz.cfc.androidgp.sightwordslite-2023000.apk.cg.txt -app cz.cfc.androidgp.sightwordslite-2023000.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/de.daboapps.mathematics-19.apk.cg.txt -app de.daboapps.mathematics-19.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/de.devmil.minimaltext-442.apk.cg.txt -app de.devmil.minimaltext-442.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/devdnua.cookbook-7.apk.cg.txt -app devdnua.cookbook-7.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/digifit.virtuagym.client.android-347000.apk.cg.txt -app digifit.virtuagym.client.android-347000.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/epic.mychart.android.apk.cg.txt -app epic.mychart.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/eu.lequem.sgptviewer-73.apk.cg.txt -app eu.lequem.sgptviewer-73.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/fr.lehovetzki.ABMathlite-31.apk.cg.txt -app fr.lehovetzki.ABMathlite-31.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/fr.snapp.fidme-470.apk.cg.txt -app fr.snapp.fidme-470.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/gbis.gbandroid.apk.cg.txt -app gbis.gbandroid.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/gov.irs-17.apk.cg.txt -app gov.irs-17.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/ipnossoft.rma.free.apk.cg.txt -app ipnossoft.rma.free.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/ipnossoft.rma.oriental-9.apk.cg.txt -app ipnossoft.rma.oriental-9.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/jp.gocro.smartnews.android-89.apk.cg.txt -app jp.gocro.smartnews.android-89.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/jp.naver.line.android.apk.cg.txt -app jp.naver.line.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/jqsoft.apps.periodictable.hd-41.apk.cg.txt -app jqsoft.apps.periodictable.hd-41.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/kr.core.technology.wifi.hotspot-57.apk.cg.txt -app kr.core.technology.wifi.hotspot-57.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/kr.co.smartstudy.bodlebookiapfree_us_android_googlemarket-4700.apk.cg.txt -app kr.co.smartstudy.bodlebookiapfree_us_android_googlemarket-4700.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/kr.co.smartstudy.phonicsiap_android_googlemarket-1000.apk.cg.txt -app kr.co.smartstudy.phonicsiap_android_googlemarket-1000.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/me.keepy-2026.apk.cg.txt -app me.keepy-2026.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/me.lyft.android.apk.cg.txt -app me.lyft.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/net.daum.android.solmail-160.apk.cg.txt -app net.daum.android.solmail-160.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/net.frankensound.songofree-4.apk.cg.txt -app net.frankensound.songofree-4.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/net.hexage.radiant.lite-231904.apk.cg.txt -app net.hexage.radiant.lite-231904.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/net.lovoo.android.apk.cg.txt -app net.lovoo.android.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/net.metapps.meditationsounds.apk.cg.txt -app net.metapps.meditationsounds.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/net.uloops.android-115.apk.cg.txt -app net.uloops.android-115.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/org.catrobat.catroid-21.apk.cg.txt -app org.catrobat.catroid-21.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/org.dnalc.threedbrain-3.apk.cg.txt -app org.dnalc.threedbrain-3.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/org.mozilla.firefox.apk.cg.txt -app org.mozilla.firefox.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/org.mrchops.android.digihud-38.apk.cg.txt -app org.mrchops.android.digihud-38.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/placeholder -app placeholder
python load_database.py -jf ../android-callgraph/output/ru.mamba.client-2208.apk.cg.txt -app ru.mamba.client-2208.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/slide.camZoomFree-122.apk.cg.txt -app slide.camZoomFree-122.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/thecouponsapp.coupon-996.apk.cg.txt -app thecouponsapp.coupon-996.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/thehunt.shoptap.thehunt-47.apk.cg.txt -app thehunt.shoptap.thehunt-47.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/widget.weather.forecast-1.apk.cg.txt -app widget.weather.forecast-1.apk.cg.txt
python load_database.py -jf ../android-callgraph/output/wp.wattpad.apk.cg.txt -app wp.wattpad.apk.cg.txt
