#!/bin/bash
# find . -type f > apk.list.txt

python3 get_callgraph.py -a ../../apks/business/com.box.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/business/com.concur.breeze-37150220.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/business/com.infraware.office.link-43.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/business/com.mobisystems.office-2741.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/business/com.squareup.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/health-and-fitness-apps/com.skimble.workouts-61.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/health-and-fitness-apps/com.northpark.pushups-57.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/health-and-fitness-apps/com.caynax.a6w-80406.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/health-and-fitness-apps/digifit.virtuagym.client.android-347000.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/health-and-fitness-apps/com.northpark.drinkwater-74.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/stress-relievers/net.metapps.meditationsounds.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/stress-relievers/ipnossoft.rma.oriental-9.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/stress-relievers/ipnossoft.rma.free.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/stress-relievers/com.tmsoft.whitenoise.lite.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/stress-relievers/com.yoga.pro.google.paid-10050.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/healthy-cooking/devdnua.cookbook-7.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/healthy-cooking/com.mindframedesign.cheftap.beta-347.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/healthy-cooking/com.fooducate.nutritionapp-212.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/healthy-cooking/com.mufumbo.android.recipe.search.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/healthy-cooking/com.scripps.android.foodnetwork-403000.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/get-outside-and-play/com.mapmywalk.android2.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/get-outside-and-play/com.augmentra.viewranger.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/get-outside-and-play/com.fitnesskeeper.runkeeper.pro.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/get-outside-and-play/com.mapmyhike.android2.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/weight-loss/com.myfitnesspal.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/weight-loss/com.popularapp.sevenmins-31.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/weight-loss/com.fatsecret.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/weight-loss/com.dietcoacher.sos.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/health-and-fitness/weight-loss/com.fitnow.loseit-138.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/entertainment/com.hulu.plus-202193.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/entertainment/com.fox.now-2089.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/entertainment/com.netflix.mediaclient.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/entertainment/com.disney.disneymoviesanywhere_goo-195.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/entertainment/com.google.android.apps.youtube.kids-70505000.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/news-and-magazines/jp.gocro.smartnews.android-89.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/news-and-magazines/com.foxnews.android-200080.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/news-and-magazines/com.drippler.android.updates.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/news-and-magazines/com.cnn.mobile.android.phone.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/news-and-magazines/com.yahoo.mobile.client.android.yahoo.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/live-wallpaper/com.cootek.smartinputv5.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/live-wallpaper/com.ksmobile.launcher.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/live-wallpaper/com.devuni.flashlight-170.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/live-wallpaper/com.emoji.coolkeyboard-11.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/live-wallpaper/com.picsart.studio.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/shopping/thehunt.shoptap.thehunt-47.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/shopping/com.jackthreads.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/shopping/com.etsy.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/shopping/com.thefancy.app-29601.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/shopping/com.modcloth-75.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/retail/com.boxed.prod.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/retail/com.overstock-295000.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/retail/com.walmart.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/retail/com.liketwice.android-34.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/retail/com.google.zxing.client.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/coupon-apps/com.whaleshark.retailmenot-40301.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/coupon-apps/com.groupon.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/coupon-apps/fr.snapp.fidme-470.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/coupon-apps/thecouponsapp.coupon-996.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/shopping/coupon-apps/com.coupons.ciapp.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/photo-and-video-sharing/com.kicksend.android-470.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/photo-and-video-sharing/com.alensw.PicFolder-154.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/photo-and-video-sharing/com.mobli.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/photo-and-video-sharing/com.muzy-59.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/photo-and-video-sharing/com.photoaffections.freeprints-3667.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/social-apps/com.quoord.tapatalkpro.activity.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/social-apps/com.zoosk.zoosk.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/social-apps/com.snapchat.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/social-apps/com.instagram.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/social-apps/com.discovercircle10-100.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/mail-clients/com.fsck.k9.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/mail-clients/net.daum.android.solmail-160.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/mail-clients/com.yahoo.mobile.client.android.mail.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/mail-clients/com.syntomo.email-525060.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/mail-clients/com.cloudmagic.mail-126.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/memory-keeping-apps/com.somcloud.somnote-2015021518.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/memory-keeping-apps/com.timehop-283.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/memory-keeping-apps/com.roveapp.rove-45.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/memory-keeping-apps/me.keepy-2026.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/memory-keeping-apps/com.fancred.android-82.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/texting/com.judas.apps.calling.video-2.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/texting/com.bsb.hike.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/texting/com.textra-22692.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/texting/com.hellotext.hello-189.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/texting/com.p1.chompsms-9064206.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/video-calling/com.imo.android.imoim.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/video-calling/com.google.android.talk.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/video-calling/com.skype.android.qik-5240.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/video-calling/jp.naver.line.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/video-calling/com.textmeinc.textme.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/communication-apps/org.mozilla.firefox.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/communication-apps/com.viber.voip-89.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/communication-apps/kr.core.technology.wifi.hotspot-57.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/communication-apps/com.google.android.apps.googlevoice-40601.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/communication/communication-apps/com.google.android.apps.messaging.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/photography/photo-filters-and-editors/com.jessdev.socphotoeff-10303.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/photography/photo-filters-and-editors/com.axiemsystems.photoeditorminus-110.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/photography/photo-filters-and-editors/com.baiwang.instablend-20.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/photography/photo-filters-and-editors/com.baseapp.eyeem.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/photography/photo-filters-and-editors/com.adobe.psmobile-18.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/photography/photography/com.gopro.smarty.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/photography/photography/slide.camZoomFree-122.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/photography/photography/com.venticake.retrica-26.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/photography/photography/com.vtcreator.android360.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/photography/photography/com.google.android.GoogleCamera-24025130.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/productivity/document-editing/com.naturalapps.notas-14.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/productivity/document-editing/com.microsoft.office.onenote-1532321047.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/productivity/document-editing/com.microsoft.office.officehub-15704500.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/productivity/document-editing/com.foxit.mobile.pdf.lite-18.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/productivity/document-editing/com.quip.quip.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/productivity/productivity/com.dropbox.android-240810.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/productivity/productivity/com.basecamp.app-49.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/productivity/productivity/com.evernote.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/productivity/productivity/com.teamviewer.teamviewer.market.mobile.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/productivity/productivity/com.touchtype.swiftkey.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/comics/com.notabasement.mangarock.android.mckinley-29.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/comics/com.krivoz.submangareader-85.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/comics/com.loudcrow.marvelavengers-3.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/comics/com.crunchyroll.crmanga-17.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/comics/com.marvel.comics-37033.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/weather/widget.weather.forecast-1.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/weather/com.droid27.transparentclockweather-96.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/weather/com.accuweather.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/weather/com.weather.Weather.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/weather/com.aws.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/personalization/widgets/com.anddoes.fancywidgets-22.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/personalization/widgets/com.buzzpia.aqua.appwidget.clock-2126.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/personalization/widgets/com.slidelock-58.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/personalization/widgets/com.campmobile.launcher-69.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/personalization/widgets/com.sonyericsson.digitalclockwidget2-83.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/personalization/personalization/com.teslacoilsw.launcher-33000.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/personalization/personalization/com.SkyDivers.asteroids3d-131.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/personalization/personalization/com.WaterfallLiveWallpaperHDHQ-15.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/personalization/personalization/de.devmil.minimaltext-442.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/personalization/personalization/alpha.aquarium.hd.livewallpaper.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/sports/com.fivemobile.thescore.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/sports/com.gotv.nflgamecenter.us.lite.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/sports/air.WatchESPN-2100049.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/sports/com.foxsports.android-20.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/sports/com.espn.score_center-595.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/games/com.emflag.mahjongmaster-26.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/games/com.cgames.minesweeper-31.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/games/com.namcobandaigames.pacmantournaments-101.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/games/net.hexage.radiant.lite-231904.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/games/com.dsd164.snake97-8.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/games/com.ea.game.tetris2011_na-1410.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/games/com.bigduckgames.flow-29.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/little-book-worms/cz.cfc.androidgp.sightwordslite-2023000.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/little-book-worms/com.learninga_z.onyourown-40.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/little-book-worms/kr.co.smartstudy.bodlebookiapfree_us_android_googlemarket-4700.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/little-book-worms/com.socratica.mobile.learnalphabet.free-15.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/little-book-worms/kr.co.smartstudy.phonicsiap_android_googlemarket-1000.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/math-whizzes/com.brainpop.brainpopfeaturedmovieandroid-16.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/math-whizzes/de.daboapps.mathematics-19.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/math-whizzes/com.visionobjects.calculator.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/math-whizzes/com.headupgames.bridgeconstructorplaygroundfree-104011.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/stem-made-fun/com.escapistgames.starchart.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/stem-made-fun/com.isbx.pasco.Spark-22007.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/stem-made-fun/jqsoft.apps.periodictable.hd-41.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/stem-made-fun/org.catrobat.catroid-21.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/stem-made-fun/org.dnalc.threedbrain-3.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/apps-for-teachers/com.masteryconnect.NGSS-17.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/apps-for-teachers/com.teachersparadise.iGradr-2.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/apps-for-teachers/com.booktrack.gelada.edu-7.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/apps-for-teachers/com.sjInnovation.tpt-4.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/apps-for-teachers/com.socrative.teacher-24.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/1-2-3-go/air.intergraphics.mentalMath.Multiplication.Demo-4000000.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/1-2-3-go/com.tenmonkeys.multiplication-3.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/1-2-3-go/com.whisperarts.kids.math-16.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/1-2-3-go/fr.lehovetzki.ABMathlite-31.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/1-2-3-go/com.infinut.kindergarten.math.free-540.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/unleash-creativity/com.modelmakertools.simplemindfree-21.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/unleash-creativity/com.brakefield.idfree-59.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/unleash-creativity/com.tellagami.Tellagami-51.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/education/unleash-creativity/com.wevideo.mobile.android-55.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/transportation/com.ubercab.driver-39.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/transportation/com.thetransitapp.droid-1436.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/transportation/me.lyft.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/transportation/com.ubercab.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/transportation/org.mrchops.android.digihud-38.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/tools/com.jb.emoji.gokeyboard.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/tools/com.cleanmaster.mguard.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/tools/com.lazyswipe-1611.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/tools/com.cleanmaster.security.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/tools/com.qihoo.security-60.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/social/dating/com.pof.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/social/dating/com.meetup-188.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/social/dating/com.okcupid.okcupid.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/social/dating/ru.mamba.client-2208.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/social/dating/net.lovoo.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/social/social/com.foursquare.robin.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/social/social/com.myyearbook.m.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/social/social/com.minus.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/social/social/com.nextdoor-46.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/social/social/com.banjo.android-68.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/books-and-reference/wp.wattpad.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/books-and-reference/com.sirma.mobile.bible.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/books-and-reference/com.amazon.kindle.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/books-and-reference/bn.ereader.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/books-and-reference/com.audible.application.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/lifestyle/com.andromo.dev230101.app300711-10.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/lifestyle/com.adsk.instructables-2000004.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/lifestyle/com.yooiistudios.morningkit-58.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/lifestyle/com.autodesk.homestyler-42.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/lifestyle/com.speaktoit.assistant.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/travel-and-local/com.grubhub.android-17000000.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/travel-and-local/com.mapquest.android.ace.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/travel-and-local/com.joelapenna.foursquared-2015022723.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/travel-and-local/com.tripadvisor.android.apps.cityguide.catalog-10.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/travel-and-local/com.waze.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/travel-and-local/gbis.gbandroid.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/travel-and-local/com.google.android.apps.maps.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/travel-and-local/com.yelp.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/medical/com.hp.pregnancy.lite-45.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/medical/com.goodrx.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/medical/com.carezone.caredroid.careapp.medications-34902.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/medical/com.jardogs.fmhmobile-88.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/medical/epic.mychart.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/popular-music-apps/com.shazam.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/popular-music-apps/com.google.android.music.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/popular-music-apps/com.soundcloud.android.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/popular-music-apps/com.lava.music-15.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/popular-music-apps/com.singlecellsoftware.caustic-19.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/making-music/com.beatronik.djstudiodemo-114.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/making-music/com.korhaan.sequencer-5.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/making-music/com.planeth.rhythm-170.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/making-music/com.magix.android.mmjam-140011600.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/making-music/net.uloops.android-115.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/aspiring-guitarist/com.rubycell.perfectguitar.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/aspiring-guitarist/com.webprofusion.scalex-10800.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/aspiring-guitarist/com.gismart.guitar.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/aspiring-guitarist/net.frankensound.songofree-4.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/music-and-audio/aspiring-guitarist/eu.lequem.sgptviewer-73.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/libraries-and-demo/com.google.samples.apps.cardboarddemo-150210005.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/libraries-and-demo/com.mxtech.ffmpeg.v7_vfpv3d16-83.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/libraries-and-demo/com.aviary.android.feather.plugins.stickers.free_stickers-1.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/libraries-and-demo/com.aviary.android.feather.plugins.borders.free-2.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/libraries-and-demo/com.foxfi.addon-3011.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/finance/com.infonow.bofa-1800602002.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/finance/com.paypal.android.p2pmobile-110005810.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/finance/com.google.android.apps.walletnfcrel.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/finance/com.chase.sig.android-42.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/finance/gov.irs-17.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/finance/com.wf.wellsfargomobile-1000401.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/media-and-video/com.mxtech.videoplayer.ad.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/media-and-video/com.mobilemotion.dubsmash.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/media-and-video/com.herman.ringtone.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/media-and-video/com.quvideo.xiaoying-62.apk -o ../../cgs/
python3 get_callgraph.py -a ../../apks/media-and-video/com.frostwire.android.apk -o ../../cgs/
